name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: jimleroux/portfolio:${{ github.sha }}

      - name: Run tests
        run: |
          docker run --rm -d -p 8080:80 jimleroux/portfolio:${{ github.sha }}

      - name: Wait for container to be ready
        run: sleep 5

      - name: Test running container
        run: |
          for i in {1..5}; do
            curl -f http://localhost:8080 && break || sleep 5;
          done
          if [ $? -ne 0 ]; then
            docker logs $(docker ps -q) && exit 1
          fi

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh  # Créer le répertoire .ssh s'il n'existe pas
          echo "Adding the EC2 host key to known_hosts"
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts  # Ajouter la clé de l'hôte EC2
          ssh -i private_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "
          sudo docker stop \$(sudo docker ps -q) && 
          sudo docker rm \$(sudo docker ps -a -q)
          ssh -i private_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull jimleroux/portfolio:${{ github.sha }} && docker run --rm -d -p 8080:80 jimleroux/portfolio:${{ github.sha }}"
