name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: jimleroux/portfolio:${{ github.sha }}

      - name: Run tests
        run: |
          docker run --rm -d -p 8080:80 jimleroux/portfolio:${{ github.sha }}

      - name: Wait for container to be ready
        run: sleep 5

      - name: Test running container
        run: |
          for i in {1..5}; do
            curl -f http://localhost:8080 && break || sleep 5;
          done
          if [ $? -ne 0 ]; then
            docker logs $(docker ps -q) && exit 1
          fi

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

      - name: Deploy to EC2
        run: |
          # Déploie l'application Docker sur l'instance EC2 existante
          ssh -i ~/.ssh/portfolio.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull jimleroux/portfolio:${{ github.sha }} && docker run --rm -d -p 8080:80 jimleroux/portfolio:${{ github.sha }}"
